DROP TABLE IF EXISTS `EMPLOYEES`;
CREATE TABLE EMPLOYEES
(
    EMP_ID     BIGINT NOT NULL AUTO_INCREMENT,
    NAME       VARCHAR(252),
    DEPARTMENT VARCHAR(128),
    SALARY     BIGINT,
    JOINED_ON  TIMESTAMP,
    PRIMARY KEY (EMP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, JOINED_ON)
VALUES (1, 'Nataraja G', 'Documentation', 10000, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, JOINED_ON)
VALUES (2, 'Amar M', 'Entertainment', 12000, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, JOINED_ON)
VALUES (3, 'Nagesh Y', 'Admin', 25000, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, JOINED_ON)
VALUES (4, 'Vasu V', 'Security', 2500, CURRENT_TIMESTAMP);